server.port: 8083

spring:
  application:
    name: product-catalog
  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    org.mongodb.driver.cluster: OFF

algashop:
  data-load:
    enabled: false
    auto-delete: false
    sources:
      - location: db/testdata/categories.json
        collection: categories
      - location: db/testdata/products.json
        collection: products